load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "workspace-stats_lib",
    srcs = ["main.go"],
    importpath = "olympus.fleet/00SDLC/OlympusTools/90000-Enablement-Labs/90100-Execution-Points/workspace-stats",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "workspace-stats",
    embed = [":workspace-stats_lib"],
    visibility = ["//visibility:public"],
)
